apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- authorino.kuadrant.io_authconfigs.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
- patches/webhook_in_authconfigs.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

patchesJson6902:
- path: patches/oneof_in_authconfigs.yaml
  target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: authconfigs.authorino.kuadrant.io
