[allowlist]
  description = "Global Allowlist"

  # Ignore based on any subset of the file path
  paths = [
    '''user-guides''',
    # mkdocs search index contains full text of docs including example keys/tokens from tutorials
    '''search/search_index\.json''',
  ]
        
  # Ignore based on any subset of the line
  regexes = [
  ]
