# Enables oneOf validation for the identity/authentication, metadata, authorization, and response fields.

# v1beta1
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/identity/items/oneOf
  value:
    - properties:
        name: {}
        credentials: {}
        oauth2: {}
      required: [name, oauth2]
    - properties:
        name: {}
        credentials: {}
        oidc: {}
      required: [name, oidc]
    - properties:
        name: {}
        credentials: {}
        apiKey: {}
      required: [name, apiKey]
    - properties:
        name: {}
        credentials: {}
        mtls: {}
      required: [name, mtls]
    - properties:
        name: {}
        credentials: {}
        kubernetes: {}
      required: [name, kubernetes]
    - properties:
        name: {}
        credentials: {}
        anonymous: {}
      required: [name, anonymous]
    - properties:
        name: {}
        credentials: {}
        plain: {}
      required: [name, plain]

- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/metadata/items/oneOf
  value:
    - properties:
        name: {}
        userInfo: {}
      required: [name, userInfo]
    - properties:
        name: {}
        uma: {}
      required: [name, uma]
    - properties:
        name: {}
        http: {}
      required: [name, http]

- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/authorization/items/oneOf
  value:
    - properties:
        name: {}
        opa: {}
      required: [name, opa]
    - properties:
        name: {}
        json: {}
      required: [name, json]
    - properties:
        name: {}
        kubernetes: {}
      required: [name, kubernetes]
    - properties:
        name: {}
        authzed: {}
      required: [name, authzed]

- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/response/items/oneOf
  value:
    - properties:
        name: {}
        wristband: {}
      required: [name, wristband]
    - properties:
        name: {}
        json: {}
      required: [name, json]
    - properties:
        name: {}
        plain: {}
      required: [name, plain]

- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/authorization/items/properties/json/properties/rules/items/oneOf
  value:
    - properties:
        patternRef: {}
      required: [patternRef]
    - properties:
        operator: {}
        selector: {}
        value: {}
      required: [operator, selector]
    - properties:
        all: {}
      required: [all]
    - properties:
        any: {}
      required: [any]

- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/when/items/oneOf
  value:
    - properties:
        patternRef: {}
      required: [patternRef]
    - properties:
        operator: {}
        selector: {}
        value: {}
      required: [operator, selector]
    - properties:
        all: {}
      required: [all]
    - properties:
        any: {}
      required: [any]

- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/identity/items/properties/when/items/oneOf
  value:
    - properties:
        patternRef: {}
      required: [patternRef]
    - properties:
        operator: {}
        selector: {}
        value: {}
      required: [operator, selector]
    - properties:
        all: {}
      required: [all]
    - properties:
        any: {}
      required: [any]

- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/metadata/items/properties/when/items/oneOf
  value:
    - properties:
        patternRef: {}
      required: [patternRef]
    - properties:
        operator: {}
        selector: {}
        value: {}
      required: [operator, selector]
    - properties:
        all: {}
      required: [all]
    - properties:
        any: {}
      required: [any]

- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/authorization/items/properties/when/items/oneOf
  value:
    - properties:
        patternRef: {}
      required: [patternRef]
    - properties:
        operator: {}
        selector: {}
        value: {}
      required: [operator, selector]
    - properties:
        all: {}
      required: [all]
    - properties:
        any: {}
      required: [any]

- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/response/items/properties/when/items/oneOf
  value:
    - properties:
        patternRef: {}
      required: [patternRef]
    - properties:
        operator: {}
        selector: {}
        value: {}
      required: [operator, selector]
    - properties:
        all: {}
      required: [all]
    - properties:
        any: {}
      required: [any]

# v1beta2
- op: add
  path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/authentication/additionalProperties/oneOf
  value:
    - properties:
        credentials: {}
        oauth2Introspection: {}
      required: [oauth2Introspection]
    - properties:
        credentials: {}
        jwt: {}
      required: [jwt]
    - properties:
        credentials: {}
        apiKey: {}
      required: [apiKey]
    - properties:
        credentials: {}
        x509: {}
      required: [x509]
    - properties:
        credentials: {}
        kubernetesTokenReview: {}
      required: [kubernetesTokenReview]
    - properties:
        credentials: {}
        anonymous: {}
      required: [anonymous]
    - properties:
        credentials: {}
        plain: {}
      required: [plain]

- op: add
  path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/metadata/additionalProperties/oneOf
  value:
    - properties:
        userInfo: {}
      required: [userInfo]
    - properties:
        uma: {}
      required: [uma]
    - properties:
        http: {}
      required: [http]

- op: add
  path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/authorization/additionalProperties/oneOf
  value:
    - properties:
        opa: {}
      required: [opa]
    - properties:
        patternMatching: {}
      required: [patternMatching]
    - properties:
        kubernetesSubjectAccessReview: {}
      required: [kubernetesSubjectAccessReview]
    - properties:
        spicedb: {}
      required: [spicedb]

- op: add
  path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/response/properties/success/properties/headers/additionalProperties/oneOf
  value:
    - properties:
        wristband: {}
      required: [wristband]
    - properties:
        json: {}
      required: [json]
    - properties:
        plain: {}
      required: [plain]

- op: add
  path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/response/properties/success/properties/dynamicMetadata/additionalProperties/oneOf
  value:
    - properties:
        wristband: {}
      required: [wristband]
    - properties:
        json: {}
      required: [json]
    - properties:
        plain: {}
      required: [plain]

- op: add
  path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/authorization/additionalProperties/properties/patternMatching/properties/patterns/items/oneOf
  value:
    - properties:
        patternRef: {}
      required: [patternRef]
    - properties:
        operator: {}
        selector: {}
        value: {}
      required: [operator, selector]
    - properties:
        all: {}
      required: [all]
    - properties:
        any: {}
      required: [any]

- op: add
  path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/when/items/oneOf
  value:
    - properties:
        patternRef: {}
      required: [patternRef]
    - properties:
        operator: {}
        selector: {}
        value: {}
      required: [operator, selector]
    - properties:
        all: {}
      required: [all]
    - properties:
        any: {}
      required: [any]

- op: add
  path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/authentication/additionalProperties/properties/when/items/oneOf
  value:
    - properties:
        patternRef: {}
      required: [patternRef]
    - properties:
        operator: {}
        selector: {}
        value: {}
      required: [operator, selector]
    - properties:
        all: {}
      required: [all]
    - properties:
        any: {}
      required: [any]

- op: add
  path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/metadata/additionalProperties/properties/when/items/oneOf
  value:
    - properties:
        patternRef: {}
      required: [patternRef]
    - properties:
        operator: {}
        selector: {}
        value: {}
      required: [operator, selector]
    - properties:
        all: {}
      required: [all]
    - properties:
        any: {}
      required: [any]

- op: add
  path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/authorization/additionalProperties/properties/when/items/oneOf
  value:
    - properties:
        patternRef: {}
      required: [patternRef]
    - properties:
        operator: {}
        selector: {}
        value: {}
      required: [operator, selector]
    - properties:
        all: {}
      required: [all]
    - properties:
        any: {}
      required: [any]

- op: add
  path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/response/properties/success/properties/headers/additionalProperties/properties/when/items/oneOf
  value:
    - properties:
        patternRef: {}
      required: [patternRef]
    - properties:
        operator: {}
        selector: {}
        value: {}
      required: [operator, selector]
    - properties:
        all: {}
      required: [all]
    - properties:
        any: {}
      required: [any]

- op: add
  path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/response/properties/success/properties/dynamicMetadata/additionalProperties/properties/when/items/oneOf
  value:
    - properties:
        patternRef: {}
      required: [patternRef]
    - properties:
        operator: {}
        selector: {}
        value: {}
      required: [operator, selector]
    - properties:
        all: {}
      required: [all]
    - properties:
        any: {}
      required: [any]
