---
apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: authpolicy-sample
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: toystore
  rules:
    authentication:
      "apikey":
        apiKey:
          selector: {}
        credentials:
          authorizationHeader:
            prefix: APIKEY
