apiVersion: kuadrant.io/v1alpha1
kind: DNSRecord
metadata:
  name: dnsrecord-geo.google.hcpapps.net
spec:
  endpoints:
    - dnsName: dnsrecord-geo.google.hcpapps.net
      recordTTL: 60
      recordType: CNAME
      setIdentifier: NA
      providerSpecific:
        - name: "google/geolocation-source-region"
          value: "us-east-1"
      labels:
        id: NA
      targets:
        - dnsrecord-geo.na.google.hcpapps.net
    - dnsName: dnsrecord-geo.google.hcpapps.net
      recordTTL: 60
      recordType: CNAME
      setIdentifier: EU
      providerSpecific:
        - name: "google/geolocation-source-region"
          value: "europe-west1"
      labels:
        id: EU
      targets:
        - dnsrecord-geo.eu.google.hcpapps.net
    - dnsName: dnsrecord-geo.na.google.hcpapps.net
      recordTTL: 60
      recordType: A
      setIdentifier: 172.31.0.1
      providerSpecific:
        - name: "google/weight"
          value: "60"
      labels:
        id: 172.31.0.1
      targets:
        - 172.31.0.1
    - dnsName: dnsrecord-geo.na.google.hcpapps.net
      recordTTL: 60
      recordType: A
      setIdentifier: 172.31.0.2
      providerSpecific:
        - name: "google/weight"
          value: "60"
      labels:
        id: 172.31.0.2
      targets:
        - 172.31.0.2
    - dnsName: dnsrecord-geo.eu.google.hcpapps.net
      recordTTL: 60
      recordType: A
      setIdentifier: 172.31.0.3
      providerSpecific:
        - name: "google/weight"
          value: "60"
      labels:
        id: 172.31.0.3
      targets:
        - 172.31.0.3
    - dnsName: dnsrecord-geo.eu.google.hcpapps.net
      recordTTL: 60
      recordType: A
      setIdentifier: 172.31.0.4
      providerSpecific:
        - name: "google/weight"
          value: "60"
      labels:
        id: 172.31.0.4
      targets:
        - 172.31.0.4
