apiVersion: kuadrant.io/v1alpha1
kind: DNSHealthCheckProbe
metadata:
  name: $NAME
spec:
  port: 443
  hostname: test.com
  address: 192.168.0.16
  path: /healthz
  protocol: HTTPS
  interval: 60s
  additionalHeadersRef:
    name: headers
  failureThreshold: 5
  allowInsecureCertificate: True