---
version: '3.8'
services:
  limitador:
    image: ${LIMITADOR_IMAGE:-limitador-testing}
    depends_on:
      infinispan:
        condition: service_healthy
    command:
      - limitador-server
      - --rls-ip
      - 0.0.0.0
      - --rls-port
      - "8081"
      - --http-ip
      - 0.0.0.0
      - --http-port
      - "8080"
      - -vvvv
      - --grpc-reflection-service
      - /opt/kuadrant/limits/limits.yaml
      - infinispan
      - --cache-name
      - "limitador-sandbox"
      - --consistency
      - "Strong"
      - http://username:password@infinispan:11222
    expose:
      - "8080"
      - "8081"
    ports:
      - "18080:8080"
      - "18081:8081"
    volumes:
      - ./limits.yaml:/opt/kuadrant/limits/limits.yaml
  infinispan:
    image: infinispan/server:13.0.10.Final
    environment:
      USER: username
      PASS: password
    expose:
      - "11222"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11222/rest/v2/cache-managers/default/health/status"]
      interval: 30s
      timeout: 10s
      retries: 5
