# Enables oneOf validation for the identity/metadata/authorization modes

- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/identity/items/oneOf
  value:
    - properties:
        name: {}
        credentials: {}
        oauth2: {}
      required: [name, oauth2]
    - properties:
        name: {}
        credentials: {}
        oidc: {}
      required: [name, oidc]
    - properties:
        name: {}
        credentials: {}
        apiKey: {}
      required: [name, apiKey]
    - properties:
        name: {}
        credentials: {}
        apiKey: {}
      required: [name, mtls]
    - properties:
        name: {}
        credentials: {}
        kubernetes: {}
      required: [name, kubernetes]
    - properties:
        name: {}
        credentials: {}
        anonymous: {}
      required: [name, anonymous]
    - properties:
        name: {}
        credentials: {}
        anonymous: {}
      required: [name, plain]

- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/metadata/items/oneOf
  value:
    - properties:
        name: {}
        userInfo: {}
      required: [name, userInfo]
    - properties:
        name: {}
        uma: {}
      required: [name, uma]
    - properties:
        name: {}
        uma: {}
      required: [name, http]

- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/authorization/items/oneOf
  value:
    - properties:
        name: {}
        opa: {}
      required: [name, opa]
    - properties:
        name: {}
        json: {}
      required: [name, json]
    - properties:
        name: {}
        kubernetes: {}
      required: [name, kubernetes]

- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/authorization/items/properties/json/properties/rules/items/oneOf
  value:
    - properties:
        patternRef: {}
      required: [patternRef]
    - properties:
        operator: {}
        selector: {}
        value: {}
      required: [operator, selector, value]

- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/when/items/oneOf
  value:
    - properties:
        patternRef: {}
      required: [patternRef]
    - properties:
        operator: {}
        selector: {}
        value: {}
      required: [operator, selector, value]

- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/identity/items/properties/when/items/oneOf
  value:
    - properties:
        patternRef: {}
      required: [patternRef]
    - properties:
        operator: {}
        selector: {}
        value: {}
      required: [operator, selector, value]

- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/metadata/items/properties/when/items/oneOf
  value:
    - properties:
        patternRef: {}
      required: [patternRef]
    - properties:
        operator: {}
        selector: {}
        value: {}
      required: [operator, selector, value]

- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/authorization/items/properties/when/items/oneOf
  value:
    - properties:
        patternRef: {}
      required: [patternRef]
    - properties:
        operator: {}
        selector: {}
        value: {}
      required: [operator, selector, value]

- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/response/items/properties/when/items/oneOf
  value:
    - properties:
        patternRef: {}
      required: [patternRef]
    - properties:
        operator: {}
        selector: {}
        value: {}
      required: [operator, selector, value]
